### ISSUE TITLE
Pickup, drop, show inventory

### ISSUE THREAD

**Issue by nico8034** [Nicklason/worldofzuul#30]
pickup items
drop items
show current inventory

commands: pickup, drop, inv

**Comment by Nicklason** [comment]
Der skal også være en use kommando: "use boots" / "use pipe"

**Comment by nico8034** [comment]
pt i branch pickup items, arbejder videre med den i morgen, når ikke mere i dag. Men det virker som det skal :D du kan samle op og lægge tilbage så tosset du vil

**Comment by nico8034** [comment]
Det er der

**Comment by nico8034** [comment]
jeg mener det kommer der!

**Comment by Nicklason** [comment]
Bare så du ved det, så får alle en mail når du skriver en kommentar, så hvis du vil være rigtigt irriterende så skal du bare sende en masse :)
