### ISSUE TITLE
Kommandoer for at vise info om rummet man er i

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/worldofzuul#34]
Vi skal bruge kommandoer som kan fortælle info om rummet, skal vise samme info som når man skifter til et rum. Kan f.eks. tilføje det til help kommandoen, men skal nok helst lave en ny kommando til det.

**Comment by nico8034** [comment]
Den havde jeg tilføjet, den hed point og returnerede exits og pois of current room :D men den er hurtig at lave
