### ISSUE TITLE
Highscore 

### ISSUE THREAD

**Issue by nico8034** [Nicklason/worldofzuul#35]
Vi skal have lavet en metode der kan tjekke på hvert roomobject hvor mange af rummets  pointOfInterests er fixed. (Der er en isFixed metode)
På den måde kan vi give x antal point for hvert poi der er fixed.

Hvis vi opdeler resultaterne i rum kan vi bruge det til den senere iteration hvor vi skal præsentere brugeren med 1 af 3 mulige grafiske udfald pr. rum afhængig af løste points of interests

**Comment by Nicklason** [comment]
Vi kan lave en liste af rum / poi på Game klassen
