### ISSUE TITLE
Brug go til rum og poi

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/worldofzuul#45]
Syntes det er lidt for meget at skrive både go og see, måske kun brug go kommandoen?

**Comment by MargaritaMariaHansen** [comment]
God ide, jeg skriver go boat, i stedet for see boat tit, når jeg spiller. Det er mere brugervenligt med en komando - go. Men det ville måske virke som om det helle er exits...er det et problem?

**Comment by Nicklason** [comment]
Jeg syntes ikke det vil være et problem, færre kommandoer men samme funktionalitet vil fungere bedre

**Comment by nico8034** [comment]
Det er fint :)
