### ISSUE TITLE
Adgang til factory når keycard er brugt på døren

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/worldofzuul#49]
Siger at man ikke kan bruge keycard til at åbne dør til fabrikken

**Comment by nico8034** [comment]
Jeg tænker denne kan løses forholdsvis nemt, ved at tilføje en knap på døren der bare hedder fx "Enter Factory". Denne knap kan som default have en setVisible(False) og ændres til true når keycarded bruges :)

**Comment by Nicklason** [comment]
Giver ikke rigtigt mening at ændre et issue til noget helt andet, jeg skrev bare at der var et problem med at bruge keycard til døren og lavede et issue med det.

**Comment by nico8034** [comment]
Det har du ret i, jeg beklager. Dette issue var 24 dage gammelt så
genbrugte det da det nye issue omhandlede samme poi, men jeg skulle bare
have lavet et nyt 👍

fre. 6. dec. 2019 10.05 skrev Nicklas Marc Pedersen <
notifications@github.com>:
