### ISSUE TITLE
Vi skal lave et inventar

### ISSUE THREAD

**Issue by MargaritaMariaHansen** [Nicklason/worldofzuul#5]
Vi skal lave et inventar.

- Hvor stor skal den være?
- Skal det være en ArrayList eller en Array?
- Hvilke attributter skal tingene i inventar klassen have? (navn, id osv.)

**Comment by Nicklason** [comment]
Vi skal første have en grund til at lave et inventar, det kommer vi til at snakke om i dag regner jeg med.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/worldofzuul/issues/10
