### ISSUE TITLE
Vi skal lave en start menu i Java FX

### ISSUE THREAD

**Issue by MargaritaMariaHansen** [Nicklason/worldofzuul#57]
Det skal være muligt at vælge imellem:
- play
- help
- hints
- about
Man skal kunne gå tilbage til menu fra halp, hints, about.
Der skal skrives tekst i alle faner.

**Comment by nico8034** [comment]
Denne er lavet og (rigtig fin) af margarita, den skal blot samles med det andet kode. Skulle ikke være noget problem da den har sin egen controller.
Dette vil dog stille krav til singleton løsning mht instance of game. (Sådan at alle ens resultater stadig er gemt i instancen af game når man går ind i lobby for at færdiggøre spillet.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/worldofzuul/pull/67
