### ISSUE TITLE
Se hvor ting kan bruges

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/worldofzuul#59]
Hav en måde hvor at spilleren kan se hvor en ting kan bruges.

Hvis man har valgt et poi, så skal alle tingene som kan bruges ved det poi have en anden farve / noget som viser at tingen kan bruges.

Use knappen kan også blive grå hvis man ikke kan bruge den ting man har valgt.

**Comment by Nicklason** [comment]
Det bliver måske for nemt at spille spillet, fordi så skal man ikke tænke sig til hvad man skal.

**Comment by nico8034** [comment]
Ja præcis, tænker vi skipper denne så de skal tænke lidt. Funfacts og descriptions burde sammen give rigeligt med information til hvad der skal udføres.
